# hardcoded values
path = "P:\\"

filename = "guitar_practice_tracker.xlsx"

topics = {
    "Music_Theory": 0,
    "Sight Reading": 0,
    "Ear Training": 0,
    "Sight Playing (Graded Studies|Classical Pieces)": 0,
    "Kitharologus": 0,
    "Rhythm (Song) Practice": 0,
    "Lead (Song) Pieces": 0,
    "FretBoard Mastery": 0,
    "Work on Scales": 0,
    "Work on Chords": 0,
    "Arpeggios": 0,
    "Legato": 0,
    "Vibrato": 0,
    "Slide": 0,
    "Bends": 0,
    "Picado": 0,
    "Rasgeo": 0,
    "Pulgar": 0,
    "Alzapua": 0,
    "Golpe": 0,
    "Natural Harmonics": 0,
    "Artificial Harmonics": 0,
    # "Solea": 0,
    # "Alegrias": 0,
    # "Tangos": 0,
    # "Seguiriya": 0,
    # "Tarantas": 0,
    # "Granainas": 0,
    # "Bulerias": 0,
    # "Improvisation": 0,
    # "Guitar Licks": 0,
    # "Flamenco RH": 0,
    # "Flamenco LH": 0,
    # "Tremelo": 0,
    # "Sweep Picking": 0,
    # "Hybrid Picking": 0,
    # "Tapping": 0,
    # "Harp Harmonics": 0,
    # "Slap Harmonics:": 0,
    # "Percussive": 0,
    # "Whammy bar": 0,
    # "Pedals": 0,
  }